### ISSUE TITLE
Shutdown script is executed twice on ASG shutdown

### ISSUE THREAD

**Issue by ruudk** [JustScaleIt/lifecycled#5]
I run Lifecycled as a Systemd service.

When it gets a ASG shutdown lifecycle command, it starts the shutdown script.

And then waits for AWS to shutdown the instance, triggering the posix shutdown script.

But then it executes the script twice, without reason:

```
Aug 06 12:38:14 lifecycled:  Shutdown: callback start
Aug 06 12:38:14 lifecycled:  We are being told by the ASG lifecycle hook to shutdown
Aug 06 12:38:14 lifecycled:  This instance will be shut down after the shutdown callback finishes
Aug 06 12:38:14 lifecycled:  Executing script
Aug 06 12:38:15 lifecycled:  Shutdown: callback finished
Aug 06 12:38:17 systemd:  Stopping Lifecycled...
Aug 06 12:38:17 lifecycled:  Shutdown: callback start
Aug 06 12:38:17 lifecycled:  We are being signaled by a Posix signal to shutdown
Aug 06 12:38:17 lifecycled:  This process will exit after the shutdown callback finishes
Aug 06 12:38:17 lifecycled:  Executing script
```

I think Lifecycled should either unregister POSIX handler on ASG shutdown, or just shutdown itself too.

**Comment by jason-riddle** [comment]
First option makes sense to me. I feel like you would at least want one to fire off versus not doing anything and just shutting down.
